name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Build type (debug/release)'
        required: true
        default: 'release'
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android  # 全局默认目录（可选
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    # 第一步：检查是否是有效的Gradle项目
    - name: Validate Gradle Project
      id: validate-gradle
      run: |
        
        if [ -f "settings.gradle.kts" ] || [ -f "build.gradle.kts" ] || [ -f "settings.gradle" ] || [ -f "build.gradle" ]; then
          echo "is_gradle_project=true" >> $GITHUB_OUTPUT
        else
          echo "is_gradle_project=false" >> $GITHUB_OUTPUT
        fi
        echo "Initializing new Gradle project..."
        gradle init --type kotlin-application --dsl kotlin --no-daemon
         
        
    
    # 第二步：如果不是Gradle项目，先初始化
    - name: Initialize Gradle Project
      if: steps.validate-gradle.outputs.is_gradle_project == 'false'
      run: |
         ./gradlew wrapper --gradle-version 8.2
         chmod +x gradlew
    
    
    - name: Build with Gradle
      run: ./gradlew build
