name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - name: Install Flutter
     # if: false  # 为假不执行
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'  # 指定具体版本
        channel: 'stable'         # 指定渠道
     
    - uses: gradle/gradle-build-action@v2
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
 
    - name: Grant execute permission for gradlew
      working-directory: ./android  # 在这里指定工作目录
      run: |
         echo "构建gradew"
         echo "FLUTTER_HOME exists: $(ls -d $FLUTTER_HOME)"
         echo "ANDROID_HOME exists: $(ls -d $ANDROID_HOME)"
         # 在项目根目录执行（会自动重建文件）
        
         ls
         
         #gradle --version  # 应显示 8.2 或更高版本
         gradle wrapper
         chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
