name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android  # 全局默认目录（可选
   

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'  # 指定具体版本
        channel: 'stable'         # 指定渠道
      env:
        FLUTTER_HOME: ${{ github.workspace }}/flutter-sdk # 显式定义路径
        ANDROID_HOME: ${{ github.workspace }}/android-sdk

    - name: Grant execute permission for gradlew
      run: |
         echo "构建gradew"
         echo "FLUTTER_HOME exists: $(ls -d $FLUTTER_HOME)"
         echo "ANDROID_HOME exists: $(ls -d $ANDROID_HOME)"

         # 在项目根目录执行（会自动重建文件）
        
         ls
         
         #gradle --version  # 应显示 8.2 或更高版本
         gradle wrapper --gradle-version 8.14

         chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
