name: Flutter CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/git@v3
      - run: |
         git submodule add https://github.com/your/vpn-service.git vpn-service
       
      - uses: actions/checkout@v3
        with:
          submodules: recursive  # 如果使用子模块
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x'  # 指定Flutter版本
      - run: |
             flutter pub get
      - run: flutter test
