name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Build type (debug/release)'
        required: true
        default: 'release'
        type: choice
        options:
          - debug
          - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    

        
    - name: Fix Gradle Wrapper
      run: |
          if [ ! -f "gradlew" ]; then
            gradle wrapper --gradle-version 8.2
          fi
          chmod +x gradlew
          ./gradlew --version  # 验证
    - name: Setup Gradle Project
      run: |
        if [ ! -f "settings.gradle.kts" ] && [ ! -f "build.gradle.kts" ]; then
          echo "Initializing new Gradle project..."
          gradle init --type kotlin-application --dsl kotlin --no-daemon
        fi
    - name: Build with Gradle
      run: ./gradlew build
