name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Gradle Wrapper
      working-directory: ./android
      run: |
        # 下载 Gradle 包装器
        mkdir -p gradle/wrapper
        wget -O gradle/wrapper/gradle-wrapper.jar https://repo1.maven.org/maven2/org/gradle/gradle-wrapper/7.5.1/gradle-wrapper-7.5.1.jar
        wget -O gradle/wrapper/gradle-wrapper.properties https://raw.githubusercontent.com/gradle/gradle/v7.5.1/gradle/wrapper/gradle-wrapper.properties
        chmod +x gradlew

    - name: Build with Gradle
      working-directory: ./android
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: karing-debug-apk
        path: ./android/app/build/outputs/apk/debug/*.apk
